version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: adapt_db
      POSTGRES_PASSWORD: postgres

  app:
    container_name: app
    build:
      context: .
    ports:
      - "8081:8080"  # Map port 8081 on the host to 8080 in the container
    environment:
      - "POSTGRES_DB_SERVER_ADDRESS=db"
      - "POSTGRES_DB_SERVER_PORT=5432"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    depends_on:
      - db
