spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS:localhost}:${POSTGRES_DB_SERVER_PORT:5432}/${POSTGRES_DB:adapt_db}?createDatabaseIfNotExist=true
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true

springdoc:
  swagger-ui:
    path: /api-docs
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: com.adapt.boilerplate.springboot

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    org.springframework: INFO
    com.farukgenc.boilerplate.springboot: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: secret
  expirationMinute: 10

swagger:
  app-name: Spring Boot ADAPT Project
  app-description: "Spring Boot Boilerplate for ADAPT"
  app-version: 1.0.0
  app-license: Apache 2.0
